name: DrawioToRdf

on: [push]
# echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
          
jobs:
  chowlk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: convert drawio to rdf
        working-directory: ./methods
        run: |
          echo "CHANGED_FILES=(`ls ${prefix}*.drawio`)
          for f in $CHANGED_FILES; do cat f; done
