name: DrawioToRdf

on: [push]
jobs:
  chowlk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          export DIFF=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} methods/*.drawio)
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
      - name: clone Chowlk and install requirements
        #working-directory: ./methods
        if: ${{ steps.diff.outputs.diff }}
        uses: actions/checkout@master
        with:
          repository: oeg-upm/Chowlk
        run: |
          echo "${{ steps.diff.outputs.diff }}"
          pip install -r Chowlk/requirements.txt
      - name: convert drawio to rdf
        if: ${{ steps.diff.outputs.diff }}
        #working-directory: ./methods
        run: |
          for file in ${{ steps.diff.outputs.diff }}; do python Chowlk/converter.py "$file" "$file".ttl --type ontology --format ttl; done
      - name: Commit files # commit the output folder
        if: ${{ steps.diff.outputs.diff }}
        working-directory: ./methods
        run: |
          git config --local user.email "chowlk.action@github.com"
          git config --local user.name "Chowlk Action"
          git add .
          git commit -m "converted changed drawio files"  
      - name: Push changes # push the output folder to your repo
        if: ${{ steps.diff.outputs.diff }}
        uses: ad-m/github-push-action@master
        with:
          #branch: main #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
