name: DrawioToRdf

on: [push]
# echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
          
jobs:
  chowlk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: convert drawio to rdf
        working-directory: ./methods
        run: |
          echo "clone Chowlk and install requirements"
          git clone https://github.com/oeg-upm/Chowlk.git
          pip install -r Chowlk/requirements.txt
          echo "run converter on files"
          python Chowlk/converter.py DIN_EN_ISO_527-3.drawio DIN_EN_ISO_527-3.ttl --type ontology --format ttl
          echo "job done"
