name: DrawioToRdf

on: [push]
#echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV

jobs:
  chowlk:
    runs-on: ubuntu-latest
    if: $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: clone Chowlk and install requirements
        working-directory: ./methods
        run: |
          git clone https://github.com/oeg-upm/Chowlk.git
          pip install -r Chowlk/requirements.txt
      - name: convert drawio to rdf
        working-directory: ./methods
        run: |
          python Chowlk/converter.py DIN_EN_ISO_527-3.drawio DIN_EN_ISO_527-3.ttl --type ontology --format ttl
      - name: Commit files # commit the output folder
        working-directory: ./methods
        run: |
          git config --local user.email "chowlk.action@github.com"
          git config --local user.name "Chowlk Action"
          git add *.ttl
          git commit -m "converted changed drawio files"  
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          #branch: main #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
