name: DrawioToRdf

on: [push]
# echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
          
jobs:
  chowlk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: convert drawio to rdf
        working-directory: ./methods
        run: |
          git clone https://github.com/oeg-upm/Chowlk.git
          git checkout webservice
          pip install -r requirements.txt
