# workflow to submit new release to matport.org

name: Submit_to_Matportal

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: curl
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: apikey token=$API_TOKEN" https://rest.matportal.org/ontologies/MSEO/submissions -X POST -d '{"description":"MSEO utilizes the Common Core Ontology stack giving materials scientists and engineers the ability to represent their experiments and resulting data. The goal is to create machine and human readable sematic data which can be easily digested by other science domains.  It is a product joint venture Materials Open Lab Project between the Bundesanstalt für Materialforschung und -prüfung (BAM) and the Fraunhofer Group MATERIALS and used the BWMD ontology created by Fraunhofer IWM as a starting point.","hasOntologyLanguage":"OWL","contact":{"name":"Thomas Hanke","email":"thomas.hanke@materials.fraunhofer.de"},"released":"'"$(date --iso-8601=seconds)Z"'","pullLocation":"https://raw.githubusercontent.com/Mat-O-Lab/MSEO/main/MSEO_mid.ttl","version":"'"${{ github.event.release.tag_name }}"'"}'      
        env:
          API_TOKEN: ${{ secrets.MATPORTAL_TOKEN }}
