name: TestPipeline

on:
  workflow_dispatch:

env:
  #WORKING_DIR: ./examples/
  DATA_URL: 'https://github.com/Mat-O-Lab/CSVToCSVW/raw/main/examples/example-metadata.json'
  METHOD_URL: 'https://github.com/Mat-O-Lab/MSEO/raw/main/methods/DIN_EN_ISO_527-3.drawio.ttl'

jobs:
  TestPipeline:
    runs-on: ubuntu-latest
    services:
      csvtocsvw:
        image: ghcr.io/mat-o-lab/csvtocsvw:latest
        ports:
           - 5001:5000

      maptomethod:
        image: ghcr.io/mat-o-lab/maptomethod:latest
        ports:
           - 5002:5000
    steps:
      - name: run test
        run: |
          RESULT=$(curl -X POST "http://localhost:5001/api" -H  "accept: application/json" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"data_url\":\"https://github.com/Mat-O-Lab/CSVToCSVW/raw/main/examples/$file\"}")
          FILEDATA=$(echo $RESULT | jq -r '.filedata')
          FILENAME=$(echo $RESULT | jq -r '.filename')
          echo $FILENAME
          echo $FILEDATA > $FILENAME               
          #RESULT=$(curl -X 'GET' 'http://localhost:5001/api/informationbearingentities?url=${{env.DATA_URL}}' -H 'accept: */*')
          #echo $RESULT
            
