name: TestPipeline

on:
  workflow_dispatch:

env:
  WORKING_DIR: ./tools/examples/
  RAW_URL: 'https://github.com/Mat-O-Lab/CSVToCSVW/raw/main/examples/example.csv'
  MAPREQUEST_URL: 'https://github.com/Mat-O-Lab/MapToMethod/raw/main/examples/request.json'
  METHOD_URL: 'https://github.com/Mat-O-Lab/MSEO/raw/main/methods/DIN_EN_ISO_527-3.drawio.ttl'

jobs:
  TestPipeline:
    runs-on: ubuntu-latest
    working-directory: ${{env.WORKING_DIR}}
    services:
      csvtocsvw:
        image: ghcr.io/mat-o-lab/csvtocsvw:latest
        ports:
           - 5001:5000

      maptomethod:
        image: ghcr.io/mat-o-lab/maptomethod:latest
        ports:
           - 5002:5000
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: create csvw json-ld meta data
        run: |
          curl -LJO ${{env.RAW_URL}}
          RESULT=$(curl -X POST "http://localhost:5001/api" -H  "accept: application/json" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"data_url\":\"${{env.RAW_URL}}\"}")
          FILEDATA=$(echo $RESULT | jq -r '.filedata')
          FILENAME=$(echo $RESULT | jq -r '.filename')
          echo $FILENAME
          echo $FILEDATA > $FILENAME               
      - name: create a YARRRML mapping file
        run: |
          curl  -LJO ${{env.MAPREQUEST_URL}}
          cat request.json
          RESULT=$(curl -X 'POST' \
            'http://localhost:5002/api/mappingfile' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d @request.json -v --connect-timeout 5)
          FILEDATA=$(echo $RESULT | jq -r '.filedata')
          FILENAME=$(echo $RESULT | jq -r '.filename')
          echo $FILENAME
          echo $FILEDATA > $FILENAME
      - name: Commit files # commit the output folder
        uses: EndBug/add-and-commit@v9
        with:
          message: 'updated example output'
          add: '*.* --force'
          cwd: ${{env.WORKING_DIR}}
            
